### ISSUE TITLE
The type or namespace name 'UTJ' could not be found

### ISSUE THREAD

**Issue by Brun0oO** [katsumasa/UnityChoseKun#67]
Hi,

I tried using your addon. I imported your repository into the Asset folder of my Unity project (unity version 2020.3.43f1). I followed your recommendations for project settings. 

I have the following errors in my console :

Assets\UnityChoseKun\Runtime\Scripts\UnityChoseKunPlayer.cs(14,40): error CS0246: The type or namespace name 'UTJ' could not be found (are you missing a using directive or an assembly reference?)

Assets\UnityChoseKun\Runtime\Scripts\UnityChoseKunPlayer.cs(94,33): error CS0115: 'UnityChoseKunPlayer.OnEnable()': no suitable method found to override

Did I miss something ? 
Thank you

**Comment by katsumasa** [comment]
Hi, @Brun0oO 

UnityChoseKun uses a separate RemoteConnect package. Please obtain it together with UnityChoseKun. Setup is completed by adding the obtained package to any Unity project.

```
git clone https://github.com/katsumasa/RemoteConnect.git
```
