### ISSUE TITLE
RigidboyKun.csでRigidbodyの参照不明なプロパティにアクセスしようとしています

### ISSUE THREAD

**Issue by Yothuba3** [katsumasa/UnityChoseKun#74]
Packages\com.utj.unitychosekun@faec287eca\Runtime\Scripts\Component\RigidbodyKun.cs(68,27): error CS1061: 'Rigidbody' does not contain a definition for 'linearDamping' and no accessible extension method 'linearDamping' accepting a first argument of type 'Rigidbody' could be found (are you missing a using directive or an assembly reference?)

Packages\com.utj.unitychosekun@faec287eca\Runtime\Scripts\Component\RigidbodyKun.cs(69,27): error CS1061: 'Rigidbody' does not contain a definition for 'angularDamping' and no accessible extension method 'angularDamping' accepting a first argument of type 'Rigidbody' could be found (are you missing a using directive or an assembly reference?)

**Comment by Yothuba3** [comment]
Unity editor  2022.3.53f1

**Comment by katsumasa** [comment]
Thank you for reporting this.
It has been fixed in v0.2.7.
https://github.com/katsumasa/UnityChoseKun/releases/tag/v0.2.7
